### ISSUE TITLE
2024/09/06 (금) 발표 준비

### ISSUE THREAD

**Issue by everydayday** [jokim-bizarre-adventure/backend#9]
### 📢 About
각자 맡은 바 정리해서 comment에 올려주세요.
(형식 자유)

### 📜 To do
- [x] (김대희) 작성한 백엔드 관련 코드 설명
- [x] (김성수) 작성한 백엔드 관련 코드 설명
- [x] (김규찬) 구추한 CI/CD, 작성한 백엔드 관련 코드 설명

### 🔖 Note

**Comment by aidzero01** [comment]
![image](https://github.com/user-attachments/assets/bc1c7bdd-7801-49c4-9fe5-cced365182f8)

로그인과 회원가입 구현. 로그인시 jwt accessToken과 refresh토큰 생성해서 refresh의 경우 redis에 등록해서 관리
accesstoken안에는 회원의 uuid와 발급일자, 만료일자 등의 정보들이 들어있고, refresh토큰의 경우에는 만료일자만 들어있음
redis에 저장되는 형태는 key에는 회원의 uuid값, value에는 refresh토큰이 들어있음
기본적으로 access토큰의 경우에는 30분, refresh토큰의 경우 2주 정도의 만료시간을 가진다고 한다고 가정(아직 시간적인 부분은 협의가 안됨)
큰 로직은 회원이 생성한 access토큰으로 로그인인증을 하다가 accesstoken이 만료되면 redis에 저장된 회원 uuid와 refresh토큰 값을 확인하고, refresh토큰의 만료기간이 남아있다면 accessToken을 다시 발급해서 정상적인 활동을 할 수있도록 작성했음.
redis의 secret-key와 issure의 경우에는 새로 만들어 우리 프로젝트만의 고유한 키값으로 설정하면 좋을듯
근데 아직 refresh토큰의 시간이 남아있고 accesstoken이 만료되어서 다시 발급해주는 상황일 때 정상적으로 처리되는지 확인해보지 못했음. 이부분에 대해서 확인이 필요할 것 같음
또 한가지 체크를 못해본게 일정시간이 지나면 redis에 저장된 refresh토큰이 일정시간이 지나면 자동으로 삭제되는지를 체크못해봄.
체크하는 방법이 있다면 알려주십쇼..
